# Generated by Django 4.1.7 on 2023-02-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_special_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=1),
        ),
    ]
