# Generated by Django 4.1.7 on 2023-03-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_name_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_level',
            field=models.CharField(choices=[('کاربر ویژه', 'کاربر ویژه'), (None, '2'), ('کاربر معمولی', 'کاربر معمولی')], default='3', max_length=12, verbose_name='سطح کاربر'),
        ),
    ]
