# Generated by Django 4.1.7 on 2023-03-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_jamsabad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sabad',
            name='p',
            field=models.IntegerField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='sabad',
            name='p2',
            field=models.IntegerField(default=0, max_length=255),
        ),
    ]
