# Generated by Django 4.1.7 on 2023-03-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_sabad_p_sabad_p2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabad',
            name='p',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sabad',
            name='p2',
            field=models.IntegerField(default=0),
        ),
    ]
