# Generated by Django 4.1.7 on 2023-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_sabad_p_alter_sabad_p2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profile/profile.png', upload_to='profile/'),
        ),
    ]
