# Generated by Django 4.1.7 on 2023-03-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jamsabad',
            options={'verbose_name': 'جمع', 'verbose_name_plural': 'جمع سبد ها'},
        ),
        migrations.AlterModelOptions(
            name='sabad',
            options={'verbose_name': 'سبد', 'verbose_name_plural': 'سبد ها'},
        ),
    ]
