# Generated by Django 4.2 on 2023-12-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='txtmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filetxt', models.FileField(upload_to='text_files/', verbose_name='فایل تکست')),
            ],
        ),
    ]
