# Generated by Django 4.1.5 on 2023-02-01 19:44

import Product.models.products
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, verbose_name='سلاگ')),
                ('image_preview', models.ImageField(upload_to=Product.models.products.upload_path, verbose_name='تصویر پیشنمایش')),
                ('tutorial', models.CharField(max_length=100, verbose_name='نوع دوره')),
                ('small_description', models.TextField(verbose_name='توضیح کوتاه')),
                ('long_description', models.TextField(verbose_name='توضیح مفصل')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('price_percent', models.IntegerField(default=0, verbose_name='درصد تخفیف')),
                ('hot_price', models.IntegerField(blank=True, default=None, null=True, verbose_name='قیمت بگایی تخفیف')),
                ('buyers_count', models.IntegerField()),
                ('view', models.IntegerField()),
                ('student_count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
