# Generated by Django 4.1.5 on 2023-02-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_image_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_preview',
            field=models.ImageField(upload_to='images/products', verbose_name='تصویر پیشنمایش'),
        ),
    ]
