# Generated by Django 4.1.5 on 2023-02-03 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options'),
        ('Product', '0003_alter_product_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='category.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='count_lesson',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='tpye_lang',
            field=models.CharField(default='Fa', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='student_count',
            field=models.IntegerField(default=1),
        ),
    ]
