# Generated by Django 4.1.5 on 2023-02-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options'),
        ('Product', '0005_product_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buyers_count',
            field=models.IntegerField(verbose_name='تعداد خریدار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='category.category', verbose_name='دسته بندی ها'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_lesson',
            field=models.IntegerField(default=0, verbose_name='تعداد دروس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='product',
            name='student_count',
            field=models.IntegerField(default=1, verbose_name='تعداد دانشجو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tpye_lang',
            field=models.CharField(default='Fa', max_length=50, verbose_name='زبان محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.IntegerField(verbose_name='تعداد بازدید'),
        ),
    ]
