# Generated by Django 4.1.5 on 2023-02-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_buyers_count_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='videos/<django.db.models.fields.related.ForeignKey>/')),
                ('id_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product', verbose_name='آیدی محصول')),
            ],
            options={
                'verbose_name': 'ویدو',
                'verbose_name_plural': 'ویدو ها',
            },
        ),
    ]
