# Generated by Django 4.1.5 on 2023-02-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_video_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/<django.db.models.fields.CharField>/'),
        ),
    ]
