# Generated by Django 4.1.5 on 2023-02-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_video_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
