# Generated by Django 4.1.5 on 2023-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_languages_remove_category_count_and_more'),
        ('Product', '0011_delete_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='language',
            field=models.ManyToManyField(to='category.languages', verbose_name='زبان برنامه نویسی'),
        ),
    ]
