# Generated by Django 4.1.5 on 2023-02-16 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_remove_product_category_product_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyers_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count_lesson',
        ),
    ]
