# Generated by Django 4.1.7 on 2023-03-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_alter_product_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='teacher_name',
            field=models.CharField(default=None, max_length=200, verbose_name='اسم مدرس کلیپ'),
            preserve_default=False,
        ),
    ]
