# Generated by Django 4.1.7 on 2023-03-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_product_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم مدرس کلیپ')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='teacher_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='hot_price',
            field=models.IntegerField(default=0, verbose_name='قیمت بگایی تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='student_count',
            field=models.IntegerField(default=0, verbose_name='تعداد دانشجو'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tpye_lang',
            field=models.CharField(choices=[('Fa', 'فارسی'), ('En', 'انگلیسی')], default='Fa', max_length=2, verbose_name='زبان محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tutorial',
            field=models.CharField(choices=[('documnet', 'documnet'), ('video', 'video'), ('short video', 'short video'), ('package', 'package')], default='video', max_length=100, verbose_name='نوع دوره'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
