# Generated by Django 4.1.7 on 2023-03-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_teacher_remove_product_teacher_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teacher',
            new_name='teachers',
        ),
    ]
