# Generated by Django 4.1.7 on 2023-03-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0017_rename_teacher_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='teacher_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.teachers'),
        ),
    ]
