# Generated by Django 4.1.7 on 2023-03-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0019_product_tutorial_level_alter_product_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tutorial_count',
            field=models.IntegerField(default=0, verbose_name='تعداد ویديو'),
        ),
    ]
