# Generated by Django 4.1.7 on 2023-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0020_product_tutorial_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tutorial_level',
            field=models.CharField(choices=[('مبتدی', 'مبتدی'), ('متوسط', 'متوسط'), ('حرفه ای', 'حرفه ای')], default='junior', max_length=100, verbose_name='سطح دوره'),
        ),
    ]
