# Generated by Django 4.1.7 on 2023-03-22 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_languages_category'),
        ('Product', '0021_alter_product_tutorial_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('tutorials', models.ManyToManyField(to='Product.product')),
            ],
            options={
                'verbose_name': 'پکیج',
                'verbose_name_plural': 'پکیج ها',
            },
        ),
    ]
