# Generated by Django 4.1.7 on 2023-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'مدرس', 'verbose_name_plural': 'مدرس ها'},
        ),
        migrations.AlterField(
            model_name='product',
            name='hot_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت بگایی تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='درصد تخفیف'),
        ),
    ]
