# Generated by Django 4.1.7 on 2023-04-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_rename_price_percent_product_pricepercent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_preview',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
