# Generated by Django 4.2 on 2023-05-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='resualt',
            field=models.TextField(blank=True, null=True, verbose_name='به چه سطحی میرسه بعد دیدن؟'),
        ),
    ]
