# Generated by Django 4.2 on 2023-05-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_remove_product_dislikeuser_remove_product_likeuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
