# Generated by Django 4.2 on 2023-07-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0036_alter_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ips', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'ip',
                'verbose_name_plural': 'ips',
            },
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Product.ipaddress'),
        ),
    ]
