# Generated by Django 4.2 on 2023-07-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0037_ipaddress_delete_package_product_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='view',
        ),
        migrations.AddField(
            model_name='product',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='hits', to='Product.ipaddress'),
        ),
    ]
