# Generated by Django 4.2 on 2023-07-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0038_remove_product_hits_remove_product_view_product_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='view',
            new_name='viewc',
        ),
    ]
