# Generated by Django 4.2 on 2023-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0040_remove_product_tutorial_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tpye_lang',
        ),
        migrations.AlterField(
            model_name='product',
            name='tutorial',
            field=models.CharField(default='pdf', max_length=100, verbose_name='نوع دوره'),
        ),
    ]
