# Generated by Django 5.0.3 on 2024-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0042_remove_product_teacher_name_delete_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='اسلاگ'),
        ),
    ]
