# Generated by Django 4.1.5 on 2023-02-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم دسته بندی')),
                ('created', models.DateField(verbose_name='تاریخ ساخت')),
                ('hashtag', models.CharField(max_length=50, verbose_name='هشتگ انگلیسی')),
                ('status', models.BooleanField(verbose_name='وضعیت')),
                ('count', models.IntegerField(verbose_name='تعداد فراخوان')),
            ],
        ),
    ]
