# Generated by Django 4.1.5 on 2023-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameE', models.CharField(max_length=50, verbose_name='نام زبان')),
                ('nameF', models.CharField(max_length=50, verbose_name='فارسیش')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('hashtag', models.CharField(max_length=50, verbose_name='هشتگ انگلیسی')),
            ],
            options={
                'verbose_name': 'زبان برنامه نویسی',
                'verbose_name_plural': 'زبان ها',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
    ]
