# Generated by Django 4.1.5 on 2023-02-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_languages_remove_category_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='category',
            field=models.ManyToManyField(to='category.category', verbose_name='ذسته بندس ها'),
        ),
    ]
