# Generated by Django 4.1.5 on 2023-02-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='informationSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameE', models.CharField(max_length=100)),
                ('nameF', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images/logo/')),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
