# Generated by Django 4.2 on 2023-05-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsite',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
