# Generated by Django 4.2 on 2023-07-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_informationsite_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationsite',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
