# Generated by Django 4.2 on 2023-06-07 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletUser',
        ),
    ]
