# Generated by Django 4.2 on 2024-02-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_historicalpurchase_historicaltransfer_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='quantity',
        ),
    ]
