# Generated by Django 4.2 on 2024-02-26 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0004_remove_historicalpurchase_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltransfer',
            old_name='user',
            new_name='receivingـuser',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.AddField(
            model_name='historicaltransfer',
            name='senderـuser',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='receivingـuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transfer',
            name='senderـuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
