# Generated by Django 4.2 on 2024-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_user_historicaltransfer_receivingـuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='type',
            field=models.CharField(default='خرید', max_length=4),
        ),
        migrations.AddField(
            model_name='historicaltransfer',
            name='type',
            field=models.CharField(default='انتقال', max_length=6),
        ),
        migrations.AddField(
            model_name='purchase',
            name='type',
            field=models.CharField(default='خرید', max_length=4),
        ),
        migrations.AddField(
            model_name='transfer',
            name='type',
            field=models.CharField(default='انتقال', max_length=6),
        ),
    ]
