# Generated by Django 4.2 on 2024-02-27 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0042_remove_product_teacher_name_delete_teachers'),
        ('wallet', '0006_historicalpurchase_type_historicaltransfer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTransfer_Purchase_history',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount_send', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_Pur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(blank=True, editable=False)),
                ('type', models.CharField(choices=[('send', 's'), ('purchase', 'p')], max_length=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_Pur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Product.product')),
                ('receivingـuser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('senderـuser', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_Pur', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical انتقال',
                'verbose_name_plural': 'historical انتقال ها',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transfer_Purchase_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_send', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_Pur', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('send', 's'), ('purchase', 'p')], max_length=8)),
                ('product_Pur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('receivingـuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('senderـuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_Pur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'انتقال',
                'verbose_name_plural': 'انتقال ها',
            },
        ),
        migrations.RemoveField(
            model_name='historicaltransfer',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaltransfer',
            name='receivingـuser',
        ),
        migrations.RemoveField(
            model_name='historicaltransfer',
            name='senderـuser',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='receivingـuser',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='senderـuser',
        ),
        migrations.DeleteModel(
            name='HistoricalPurchase',
        ),
        migrations.DeleteModel(
            name='HistoricalTransfer',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
