# Generated by Django 4.2 on 2024-02-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_historicaltransfer_purchase_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltransfer_purchase_history',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical انتقال و خرید ', 'verbose_name_plural': 'historical انتقال و خرید ها'},
        ),
        migrations.AlterModelOptions(
            name='transfer_purchase_history',
            options={'verbose_name': 'انتقال و خرید ', 'verbose_name_plural': 'انتقال و خرید ها'},
        ),
        migrations.AlterField(
            model_name='historicaltransfer_purchase_history',
            name='type',
            field=models.CharField(choices=[('s', 'send'), ('p', 'purchase')], max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer_purchase_history',
            name='type',
            field=models.CharField(choices=[('s', 'send'), ('p', 'purchase')], max_length=8),
        ),
    ]
