# Generated by Django 4.2 on 2024-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_historicaltransfer_purchase_history_user_main_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransfer_purchase_history',
            name='type',
            field=models.CharField(choices=[('انتقال', 'انتقال'), ('خرید', 'خرید')], max_length=8),
        ),
        migrations.AlterField(
            model_name='transfer_purchase_history',
            name='type',
            field=models.CharField(choices=[('انتقال', 'انتقال'), ('خرید', 'خرید')], max_length=8),
        ),
    ]
