# Generated by Django 4.2 on 2023-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0036_alter_comment_date'),
        ('hesab', '0003_user_githublink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='special_user',
        ),
        migrations.AddField(
            model_name='user',
            name='prod',
            field=models.ManyToManyField(blank=True, to='Product.product', verbose_name='خریذاری شذه'),
        ),
    ]
