# Generated by Django 4.2 on 2023-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0006_tickets_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='subject',
            field=models.CharField(max_length=20),
        ),
    ]
