# Generated by Django 4.2 on 2023-06-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0007_alter_tickets_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
