# Generated by Django 4.2 on 2023-12-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0041_remove_product_tpye_lang_alter_product_tutorial'),
        ('hesab', '0008_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='prod',
            field=models.ManyToManyField(blank=True, to='Product.product', verbose_name='خریداری شده'),
        ),
    ]
