# Generated by Django 4.2 on 2024-02-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0009_alter_user_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabad',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sabad',
            name='user',
        ),
        migrations.DeleteModel(
            name='jamsabad',
        ),
        migrations.DeleteModel(
            name='sabad',
        ),
    ]
