# Generated by Django 5.0.3 on 2024-08-01 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0010_remove_sabad_product_remove_sabad_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
